name: New version check

on:
  # enabling manual trigger
  workflow_dispatch:
  # running every 6 hours
  schedule:
    - cron: '48 */6 * * *'
  
jobs:
  check:
    # do not run in forks
    if: github.repository == 'PF4Public/ungoogled-chromium'
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest Linux version
        id: latest-version
        run: echo "::set-output name=version::$( curl -s https://omahaproxy.appspot.com/linux )"
      - uses: actions/checkout@v2
      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.version }}
        with:
          milestone: 1
          update_existing: false
          search_existing: all
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
