name: New version check

on:
  # enabling manual trigger
  workflow_dispatch:
  # running every 6 hours
  schedule:
    - cron: '48 */6 * * *'
  
jobs:
  check:
    # do not run in forks
    if: github.repository == 'PF4Public/ungoogled-chromium'
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest Linux version
        id: latest-version
        run: echo "::set-output name=version::$( curl -s https://omahaproxy.appspot.com/linux )"
      - uses: nickderobertis/check-if-issue-exists-action@master
        name: Check if Issue Exists
        id: check_if_issue_exists
        with:
          repo: PF4Public/ungoogled-chromium
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Updating to Chromium ${{ steps.latest-version.outputs.version }}
          labels: enhancement, help wanted
      - uses: actions/checkout@v2
        # we need this to use create-an--updating-to-chromium-x-x-x-x-.md
        # skip it if there's nothing new
        if: steps.check_if_issue_exists.outputs.exists == 'false'
      - name: Create Issue
        # skip it if there's nothing new
        if: steps.check_if_issue_exists.outputs.exists == 'false'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.latest-version.outputs.version }}
        with:
          filename:  .github/ISSUE_TEMPLATE/create-an--updating-to-chromium-x-x-x-x-.md
